# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 13:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Braşov', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student', max_length=100)),
                ('field', models.CharField(default='Informatics', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialRoommates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=datetime.date(1989, 12, 25))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=12)),
                ('description', models.TextField()),
                ('monthly_budget', models.IntegerField(default=500, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('tidyness_lvl', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('guests_lvl', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('temperament', models.CharField(choices=[('S', 'Sanguine'), ('P', 'Phlegmatic'), ('C', 'Choleric'), ('M', 'Melancholic'), ('I', 'Irelevant')], default='I', max_length=12)),
                ('is_smoker', models.BooleanField()),
                ('has_pets', models.BooleanField()),
                ('is_visible', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.City')),
                ('ocupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Ocupation')),
            ],
        ),
        migrations.AddField(
            model_name='potentialroommates',
            name='potential_roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Profile'),
        ),
    ]
