# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 11:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=datetime.date(1989, 12, 25))),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=12)),
                ('city', models.CharField(default='Braşov', max_length=100)),
                ('description', models.TextField()),
                ('ocupation', models.CharField(default='Student', max_length=100)),
                ('monthly_budget', models.IntegerField(default=500, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('tidyness_lvl', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('guests_lvl', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('temperament', models.CharField(choices=[('S', 'Sanguine'), ('P', 'Phlegmatic'), ('C', 'Choleric'), ('M', 'Melancholic'), ('Irelevant', 'I')], default='I', max_length=12)),
                ('is_smoker', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
    ]
