# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temperament',
            field=models.CharField(choices=[('S', 'Sanguine'), ('P', 'Phlegmatic'), ('C', 'Choleric'), ('M', 'Melancholic'), ('U', 'Unspecified')], default='Unspecified', max_length=12),
        ),
    ]
