# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20171209_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ocupation',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
    ]
